http:
    mappers:
        jsonPrettyPrint: true
theBigBook:
    rootDir: /home/ec2-user/app/ec2/theBigBook
spring:
    datasource:
        url: "jdbc:log4jdbc:hsqldb:file:db/ec2"
        username: root
        password:
        driverClassName: net.sf.log4jdbc.DriverSpy
    jpa:
        database-platform: org.hibernate.dialect.HSQLDialect
        show-sql: false
        hibernate:
            ddl-auto: update